import type { HairstyleCatalogItem } from "@relook/types";

/**
 * Catalogue de depart. Chaque entree n'affiche un champ `trend` que si une
 * source verifiable est fournie (voir README du catalogue) : conformement a
 * la consigne du produit, aucun style n'est ici presente comme "tendance
 * 2026/2027" sans reference. Les admins pourront enrichir ce champ via
 * l'interface d'administration en citant leurs sources (rapports de
 * tendance, defiles, etc.).
 *
 * `referenceImageUrl` pointe vers des emplacements d'assets a fournir par
 * l'equipe produit/contenu (photographies ou renders de reference reels) ;
 * ce ne sont pas des images generees ou inventees par le moteur.
 */
export const HAIRSTYLES: HairstyleCatalogItem[] = [
  {
    id: "carre-classique",
    name: "Carre classique",
    description: "Carre droit aux epaules, coupe nette et intemporelle.",
    length: "mi_courts",
    texture: "lisses",
    family: "carre",
    tags: ["intemporel", "professionnel"],
    referenceImageUrl: "/catalog/hairstyles/carre-classique.jpg",
    transformParams: { strength: 0.7, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "carre-plongeant",
    name: "Carre plongeant",
    description: "Carre plus court derriere, plus long devant, effet graphique.",
    length: "courts",
    texture: "lisses",
    family: "carre_plongeant",
    tags: ["graphique", "moderne"],
    referenceImageUrl: "/catalog/hairstyles/carre-plongeant.jpg",
    transformParams: { strength: 0.75, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "degrade-longs-ondules",
    name: "Cheveux longs degrades ondules",
    description: "Longueur, mouvement et legerete grace a un degrade progressif.",
    length: "longs",
    texture: "ondules",
    family: "degrade_longs",
    tags: ["mouvement", "feminin"],
    referenceImageUrl: "/catalog/hairstyles/degrade-longs-ondules.jpg",
    transformParams: { strength: 0.8, preserveHairline: true },
    suitableForFraming: ["portrait", "buste", "demi_corps"],
  },
  {
    id: "degrade-mi-longs-boucles",
    name: "Cheveux mi-longs degrades bouclés",
    description: "Degrade texture qui structure les boucles naturelles.",
    length: "mi_longs",
    texture: "boucles",
    family: "degrade_mi_longs",
    tags: ["naturel", "volume"],
    referenceImageUrl: "/catalog/hairstyles/degrade-mi-longs-boucles.jpg",
    transformParams: { strength: 0.75, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "pixie-courte",
    name: "Coupe pixie",
    description: "Coupe tres courte et structuree, degagee sur la nuque.",
    length: "tres_courts",
    texture: "lisses",
    family: "pixie",
    tags: ["audacieux", "facile_entretien"],
    referenceImageUrl: "/catalog/hairstyles/pixie-courte.jpg",
    transformParams: { strength: 0.85, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "bob-lisse",
    name: "Bob lisse",
    description: "Carre court au menton, tres lisse.",
    length: "courts",
    texture: "lisses",
    family: "bob",
    tags: ["chic", "minimaliste"],
    referenceImageUrl: "/catalog/hairstyles/bob-lisse.jpg",
    transformParams: { strength: 0.75, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "lob-ondule",
    name: "Lob ondule",
    description: "Long bob aux epaules avec ondulations souples.",
    length: "mi_longs",
    texture: "ondules",
    family: "lob",
    tags: ["polyvalent"],
    referenceImageUrl: "/catalog/hairstyles/lob-ondule.jpg",
    transformParams: { strength: 0.7, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "frange-droite",
    name: "Frange droite",
    description: "Frange pleine et droite, associable a toutes longueurs.",
    length: "mi_courts",
    texture: "lisses",
    family: "frange",
    tags: ["retro", "affirme"],
    referenceImageUrl: "/catalog/hairstyles/frange-droite.jpg",
    transformParams: { strength: 0.6, preserveHairline: false },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "frange-rideau",
    name: "Frange rideau",
    description: "Frange ouverte et effilee encadrant le visage.",
    length: "mi_longs",
    texture: "ondules",
    family: "frange_rideau",
    tags: ["tendance_actuelle", "doux"],
    referenceImageUrl: "/catalog/hairstyles/frange-rideau.jpg",
    transformParams: { strength: 0.6, preserveHairline: false },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "cheveux-attaches-simple",
    name: "Cheveux attaches",
    description: "Attache basse simple, look soigne et pratique.",
    length: "longs",
    texture: "lisses",
    family: "attaches",
    tags: ["pratique", "quotidien"],
    referenceImageUrl: "/catalog/hairstyles/cheveux-attaches-simple.jpg",
    transformParams: { strength: 0.65, preserveHairline: true },
    suitableForFraming: ["portrait", "buste", "demi_corps"],
  },
  {
    id: "queue-de-cheval-haute",
    name: "Queue de cheval haute",
    description: "Queue de cheval haute et lisse, effet dynamique.",
    length: "longs",
    texture: "lisses",
    family: "queue_de_cheval",
    tags: ["sport", "dynamique"],
    referenceImageUrl: "/catalog/hairstyles/queue-de-cheval-haute.jpg",
    transformParams: { strength: 0.65, preserveHairline: true },
    suitableForFraming: ["portrait", "buste", "demi_corps"],
  },
  {
    id: "chignon-bas",
    name: "Chignon bas",
    description: "Chignon souple a la nuque, elegant.",
    length: "longs",
    texture: "lisses",
    family: "chignon",
    tags: ["ceremonie", "elegant"],
    referenceImageUrl: "/catalog/hairstyles/chignon-bas.jpg",
    transformParams: { strength: 0.7, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "volume-boucles",
    name: "Coiffure avec volume boucle",
    description: "Boucles definies avec volume marque a la racine.",
    length: "mi_longs",
    texture: "boucles",
    family: "volume",
    tags: ["glamour", "soiree"],
    referenceImageUrl: "/catalog/hairstyles/volume-boucles.jpg",
    transformParams: { strength: 0.8, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
  {
    id: "afro-naturel",
    name: "Cheveux tres bouclés naturels longs",
    description: "Texture naturelle tres bouclee preservee et sublimee, forte densite.",
    length: "tres_longs",
    texture: "tres_boucles",
    family: "autre",
    tags: ["naturel", "texture_forte"],
    referenceImageUrl: "/catalog/hairstyles/afro-naturel.jpg",
    transformParams: { strength: 0.8, preserveHairline: true },
    suitableForFraming: ["portrait", "buste", "demi_corps"],
  },
  {
    id: "carre-boucle-court",
    name: "Carre court sur cheveux boucles",
    description: "Carre court qui structure une texture naturellement bouclee.",
    length: "courts",
    texture: "boucles",
    family: "carre",
    tags: ["structure", "naturel"],
    referenceImageUrl: "/catalog/hairstyles/carre-boucle-court.jpg",
    transformParams: { strength: 0.75, preserveHairline: true },
    suitableForFraming: ["portrait", "buste"],
  },
];
